### ISSUE TITLE
Saving state?

### ISSUE THREAD

**Issue by ZakTaccardi** [square/coordinators#14]
Can we get an example for saving state?

Or better yet, mirror the View's `protected` `onSaveInstanceState`/`onRestoreInstanceState` callbacks (if possible) to allow IcePick/AndroidState integration.

**Comment by loganj** [comment]
Nope! Saving state is entirely outside the scope of this library, which is one of the nice things about it.

Typically I'd have views maintain their own view state, and have the application maintain any non-view state. My coordinators are never responsible for any persistent state.
