### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "android.view.tag"

### ISSUE THREAD

**Issue by hippyk** [square/coordinators#16]
“tag“  is only used in API level 21 and higher (current min is 15)

**Comment by hippyk** [comment]
Don't you determine to support API level 19 or lower ?
I used view id instead for the low API levels .

**Comment by hippyk** [comment]
It seems not the issue of the framework. But I suggest the demo support lower api level. Level 21 is too high .

**Comment by loganj** [comment]
I think level 21 is fine for the sample. The purpose of the sample is to demonstrate one possible way to associate coordinators with views, not the only or even best way. It's trivial to implement a different mapping scheme if you want to do so to support earlier versions.
