### ISSUE TITLE
"Coordinator" is an invitation for bloat

### ISSUE THREAD

**Issue by dfed** [square/coordinators#2]
Looks like `Coordinator`s are used to bind views and values.

_Lobs live grenade_

Why not call a `Coordinator` a `ViewBinder`? Avoiding generic names like `Coordinator`, `Controller`, `Manager`, etc allow developers/reviewers to easily identify incorrectly-placed code. If I have a `NounCoordinator`, maybe the function `tellServerAboutNounChanges` belongs there. But if I have a `NounBinder`, then `tellServerAboutNounChanges` is quite clearly functionality that belongs on a different object.

**Comment by dfed** [comment]
(accidental close)

**Comment by Piasy** [comment]
I think `Coordinator` is not only a `ViewBinder`, it's something like https://github.com/trello/navi , it lets us listen to `View`'s lifecycle in pure Java class, just like navi lets us listen to `Activity`/`Fragment`'s lifecycle in pure Java class. It's not something like ButterKnife, only used to bind view and value.

Just as the README claimed, we can use `Coordinator` in our MV-whatever pattern. Let's use MVP as example, it can help us split our big MVP unit into many small MVP units, each one only cares about a small piece of views.

But actually we not only need View's lifecycle in our MVP unit, we also need Activity/Fragment's lifecycle, so we got navi to use.

**Comment by loganj** [comment]
The name is just meant to be neutral and non-prescriptive. I'm ok with renaming, but haven't heard anything that strikes me as dramatically better.  ("ViewBinder" already exists in the platform, and is a bit prescriptive.)

@piasy Can't argue with [Navi](http://github.com/trello/navi), everyone should consider it for more complex needs.

**Comment by rjrjr** [comment]
I still think `Coupling` is a better  name. Much more descriptive than `Coordinator`, and doesn't conflict with @Piasy 's concerns.

**Comment by Zhuinden** [comment]
Although by example `Coordinator` also makes sense because it coordinates Rx subscriptions and unsubscriptions, it's either Coordinator or Orchestrator but it just doesn't do enough to be called an orchestration imo

_(I'm a random bystander)_

**Comment by Zhuinden** [comment]
Technically after trying it out, it seems that Coordinators replace the "custom viewgroup" and make it directly injectable, a controller on top of the view.

It has the whole `ButterKnife.bind(this, view)` thing going on so it's actually a replacement for the view itself, and communicates with a presenter.

**Comment by loganj** [comment]
Closing this issue. Not convinced it's worthwhile to repaint the bike shed, and consumers can always subclass if they want a more specific name in their codebase.
