### ISSUE TITLE
Some questions about source code

### ISSUE THREAD

**Issue by Piasy** [square/coordinators#4]
I think `Coordinator` is really a good idea, I also plan to implement something like it. The good news is I find Coordinator before I start writing code :)

But I have some questions about Coordinator source code:

1. [In `Coordinators.bind()`](https://github.com/square/coordinators/blob/master/coordinators/src/main/java/com/squareup/coordinators/Coordinators.java#L40), the comment says:

    > Sometimes we missed the first attach because the child's already been added. Sometimes we didn't, which is why the binding keeps track and avoids double attachment.

    But the `Binding` class use `View attached` to track it and compare `attached` with the parameter `v` of view's lifecycle callback, rather than just `boolean attached`, is it the idea of defensive programming? Is it necessary?

2. [In `Binding. onViewAttachedToWindow()`](https://github.com/square/coordinators/blob/master/coordinators/src/main/java/com/squareup/coordinators/Binding.java#L31), it compares with `v.equals(attached)`, but [in `Binding. onViewDetachedFromWindow()`](https://github.com/square/coordinators/blob/master/coordinators/src/main/java/com/squareup/coordinators/Binding.java#L44), it compares with `v == attached`, that's suspicious.

3. `Coordinator.isAttached()` is final, but `Coordinator.setAttached` is not final, although it's package private, but why not make it final too?

**Comment by loganj** [comment]
Wow, thanks for the careful review!  I'll go point by point.

1. You're right, that comment needs to be updated. `Binding` actually uses `Coordinator#isAttached()` as a guard against attaching a _different_ view when not detached.
2. Yep, that is suspect. Should be using reference equality in both places, and maybe a `@NonNull` annotation for clarity.
3. Sure, why not?

PR incoming!

**Comment by loganj** [comment]
Changes are merged. Thanks again, @Piasy!
